version: '3.7'
services: 
  mysql-wms:
    image: mysql:5.7
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: simple_wms
    ports: 
        - "3306:3306"
  be-wms:
    build: 
      context: ./be-wms
    env_file: 
        -  "./be-wms/.env"
    ports: 
        - "3000:3000"
    depends_on: 
        - mysql-wms
    volumes: 
        - "./:/app/"
    
    